require("dotenv").config();
const express = require("express");
const cors = require("cors");
const app = express();
const connection = require("./db/connection");
const routes = require("./routers/route");
connection();
app.use(cors());
app.use(express.json());
app.use("/", routes);
app.listen(3000);
