const router = require("express").Router();
const online = require("./online");
const register = require("./register");
const login = require("./login");
const users = require("./users");
const refresh = require("./refresh");
router.use("/", online);
router.use("/", register);
router.use("/", login);
router.use("/", users);
router.use("/", refresh);
module.exports = router;